spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true